services:
  db:
    image: postgres:latest
    container_name: copo-postgres
    environment:
      POSTGRES_USER: satoshi
      POSTGRES_PASSWORD: 2theMOON
      POSTGRES_DB: copo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
    driver: local
