package org.acme.wallet.mapper;

import org.acme.wallet.api.contract.WalletResponse;
import org.acme.wallet.model.WalletModel;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * A MapStruct Mapper interface responsible for translating between core domain models
 * and external data transfer objects (DTOs) for the Wallet API.
 * <p>
 * MapStruct generates the implementation code for this interface during the
 * build process, eliminating manual mapping boilerplate.
 */
@Mapper
public interface WalletMapper {

    /**
     * Singleton instance of the WalletMapper implementation generated by MapStruct.
     * <p>
     * This is the standard way to access a MapStruct mapper in static contexts, such as
     * within JAX-RS resources.
     */
    WalletMapper INSTANCE = Mappers.getMapper(WalletMapper.class);

    /**
     * Converts a domain-layer {@link WalletModel} into an API-layer {@link WalletResponse}.
     * <p>
     * The generated implementation will automatically map fields with identical names
     * and compatible types (e.g., address) and handle necessary conversions (e.g.,
     * mapping the raw public key bytes from the KeyPair in WalletModel to the
     * public_key field in WalletResponse).
     *
     * @param walletModel The core domain model containing the wallet data.
     * @return A {@link WalletResponse} DTO ready to be returned via the API.
     */
    WalletResponse modelToResponse(WalletModel walletModel);
}
